# Generated by Django 5.2.5 on 2025-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do fornecedor', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Nome da pessoa de contato', max_length=255)),
                ('email', models.EmailField(help_text='E-mail para contato', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Telefone para contato', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
