# Generated by Django 5.2.5 on 2025-09-03 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Nome do cliente', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('total_price_cents', models.PositiveIntegerField(default=0, help_text='Preço total em centavos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_cents_at_time_of_order', models.PositiveIntegerField(help_text='Preço do item em centavos no momento do pedido')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product')),
            ],
        ),
    ]
