# Generated by Django 5.2.5 on 2025-09-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_alter_product_image_url_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código de barras (EAN/GTIN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, max_length=8, verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
