# Generated by Django 5.2.5 on 2025-09-05 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_cest_product_ean_product_ncm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ean',
        ),
        migrations.AddField(
            model_name='product',
            name='cfop',
            field=models.CharField(blank=True, default='', help_text='CFOP (4 dígitos)', max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='depth_cm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profundidade (cm)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, default='', help_text='GTIN/EAN (até 14 dígitos)', max_length=14),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Altura (cm)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload local (usado como prioridade sobre image_url)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0, help_text='Peso em gramas'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Largura (cm)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Preço do item (centavos) no momento do pedido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cest',
            field=models.CharField(blank=True, default='', help_text='CEST (7 dígitos)', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='URL externa opcional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.CharField(blank=True, default='', help_text='NCM (8 dígitos)', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
