# Generated by Django 5.2.5 on 2025-09-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_ean_product_cfop_product_depth_cm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cest',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depth_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_grams',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_cm',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_cents',
            field=models.PositiveIntegerField(help_text='Preço do item em centavos à época do pedido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Pessoa de contato', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='E-mail', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='products/media/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
