# Generated by Django 5.2.5 on 2025-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_product_cest_remove_product_cfop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', help_text='E-mail do cliente', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Telefone do cliente', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', help_text='Nome do cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
