# Generated by Django 5.2.5 on 2025-09-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_customer_email_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, default='', max_length=120)),
                ('email_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_code', models.CharField(blank=True, default='', max_length=6)),
                ('phone_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='Nome do cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('', 'N/D')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('canceled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
    ]
